### ISSUE TITLE
Add syntax highlighting for code

### ISSUE THREAD

**Issue by aviaryan** [mohitkyadav/algos-ngular#3]
There are lots of JS code highlighting libraries like PrismJS, HighlightJS.

**Comment by mohitkyadav** [comment]
@aviaryan sir, I've added syntax highlighting, please check https://mohitkyadav.github.io/algos-ngular/
There's a problem I am only able to highlight css, javascript and clike. I am using prismjs npm package.
`this.code_js = Prism.highlight(data, Prism.languages.javascript)` WORKS
`this.code_js = Prism.highlight(data, Prism.languages.clike)` WORKS
`this.code_js = Prism.highlight(data, Prism.languages.python)`  ERROR
`this.code_js = Prism.highlight(data, Prism.languages.go)`  ERROR
`this.code_js = Prism.highlight(data, Prism.languages.java)`  ERROR

The ERROR is 
`RROR TypeError: Cannot read property 'rest' of undefined(…)`

**Comment by aviaryan** [comment]
Prism works on the principle of brushes. You will have to include Go and Java brushes to highlight those languages.

**Comment by mohitkyadav** [comment]
Done :+1:
